//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pazzo_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class EmployeeDetail
    {
        public int Id { get; set; }
        [DisplayName("姓名")]
        public string name { get; set; }
        [DisplayName("建立日期")]
        public System.DateTime createDate { get; set; }
        [DisplayName("部門")]
        public string deptName { get; set; }
        public int deptId { get; set; }
    }
}
